[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/data/listings.js"
  [headers.values]
    Cache-Control = "public, max-age=600"
